export type CategoryId =
  | "job-interview"
  | "sales-pitch"
  | "prepared-speech"
  | "general-coaching";

export interface Category {
  id: CategoryId;
  name: string;
  description: string;
}

export interface SkillScore {
  skill: string;
  score: number; // 0-100
  note: string;
}

export interface TranscriptSegment {
  text: string;
  mark?: "strong" | "flag";
  time?: string; // mm:ss where the moment happens
  note?: string; // coach's annotation
}

/** One scored dimension of physical delivery, from the camera pass. */
export interface StageMetric {
  metric: string;
  score: number; // 0-100
  note: string;
}

/**
 * Body-language feedback (Premium). Produced by sampling frames from the
 * video track and having Felix read them alongside the audio timeline —
 * posture, sway, gestures, expression, eye contact, and what the body was
 * doing during the pauses.
 */
export interface StageAnalysis {
  overall: number; // 0-100 physical presence
  summary: string;
  metrics: StageMetric[];
  tips: string[];
}

/** A targeted practice exercise (Premium reports only). */
export interface Drill {
  title: string;
  how: string;
}

export interface Analysis {
  isSample?: boolean; // true when generated by the placeholder, not the real pipeline
  overall: number; // 0-100, computed from the dimension scores
  summary: string;
  skills: SkillScore[]; // the scored delivery dimensions
  transcript: TranscriptSegment[];
  tips: string[];
  audienceImpact?: string; // Felix's prediction of how listeners perceived it
  strengths?: string[]; // Premium: specific things done well, worth keeping
  drills?: Drill[]; // Premium: targeted practice exercises
  stage?: StageAnalysis; // present only when the user recorded with camera on
  paceWpm: number;
  fillerWords: number;
  pauses: number;
}

export type GoalId =
  | "trust"
  | "agree"
  | "inspire"
  | "leader"
  | "empathy"
  | "intelligent"
  | "memorable"
  | "calm";

export interface Goal {
  id: GoalId;
  label: string; // "Make people trust me"
}

/** Where a rep came from — drives how it's labelled and scored in Progress. */
export type PracticeMode =
  | "daily" // the universal 1-minute challenge
  | "library" // the ~30s Premium speech bank
  | "own" // the user's own material
  | "interview" // interview practice
  | "custom"; // a speech Felix wrote for this user

export interface Session {
  id: string;
  category: CategoryId;
  mode?: PracticeMode; // absent on sessions recorded before modes existed
  prompt: string;
  goal?: string; // goal label the speaker asked Felix to judge against
  speechId?: string; // set when practicing a library speech
  speechTitle?: string;
  challengeDate?: string; // YYYY-MM-DD, set on daily-challenge reps
  attempt?: number; // 1-3, set on daily-challenge reps
  interviewType?: InterviewTypeId;
  withVideo?: boolean; // camera was on (Premium)
  xpEarned?: number;
  createdAt: number; // epoch ms
  durationSec: number;
  analysis: Analysis;
}

export type InterviewTypeId =
  | "job"
  | "college"
  | "scholarship"
  | "grad-school"
  | "internship"
  | "medical-law";

export interface InterviewType {
  id: InterviewTypeId;
  name: string;
  description: string;
  questions: string[];
}
